apiVersion: v1
kind: Secret
metadata:
  name: gitlab-object-store
  namespace: gitlab
type: kubernetes.io/opaque
stringData:
  connection: |-
    provider: AWS
    region: ###ZARF_VAR_REGION###
    use_iam_profile: true
    aws_signature_version: 4
    path_style: false
  registry: |-
    s3:
      bucket: "###ZARF_VAR_REGISTRY_BUCKET###"
      region: ###ZARF_VAR_REGION###
      redirect:
        disable: true
  backups: |-
    [default]
    host_base = "s3.###ZARF_VAR_REGION###.amazonaws.com"
    host_bucket = "s3.###ZARF_VAR_REGION###.amazonaws.com"
    bucket_location = AWS
    multipart_chunk_size_mb = 128
    use_https = False
