# generated by the iac/bootstrap root module
%{ if var_prefix == null }prefix = null%{ else }prefix = "${local_prefix}"%{ endif }
%{ if var_suffix == null }suffix = null%{ else }suffix = "${local_suffix}"%{ endif }
terraform_state_bucket_name = "${terraform_state_bucket_name}"
