# If the workflow trigger is "pull_request" or "merge_group", run the pre-commit checks.
# Also run it on pushes to main, so that caches are created from the main branch, which will let child branches use them

name: pre-commit

on:
  pull_request:
  merge_group:

jobs:
  common:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: cache
        uses: ./.github/actions/cache
        with:
          action: restore
      - name: pre-commit
        uses: ./.github/actions/pre-commit
        with:
          check-type: common

  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: cache
        uses: ./.github/actions/cache
        with:
          action: restore
      - name: pre-commit
        uses: ./.github/actions/pre-commit
        with:
          check-type: terraform

  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: cache
        uses: ./.github/actions/cache
        with:
          action: restore
      - name: pre-commit
        uses: ./.github/actions/pre-commit
        with:
          check-type: renovate
